import { StyleSheet } from 'react-native';

import { theme } from './theme';

const prism = theme.prism.colors;

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: prism.background },
  loadingContainer: { alignItems: 'center', justifyContent: 'center' },
  loadingText: { color: prism.muted, fontSize: 14, marginTop: 12 },
  safeArea: { backgroundColor: prism.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 12,
  },
  headerButton: {
    width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(20, 24, 32, 0.72)',
  },
  headerTitleContainer: {
    alignItems: 'center',
    flex: 1,
  },
  stepIndicator: {
    fontSize: 12,
    color: prism.accent,
    fontWeight: '600',
    marginBottom: 4,
  },
  headerTitle: { ...theme.typography.title, fontSize: 24, lineHeight: 28, color: prism.text },
  headerHelper: { marginTop: 4, color: prism.muted, fontSize: 13, textAlign: 'center' },
  successBar: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#16a34a', paddingHorizontal: 16, paddingVertical: 10 },
  successText: { color: prism.text, fontSize: 14, fontWeight: '600' },
  content: { paddingBottom: 120 },
  bannerWrapper: { position: 'relative', marginBottom: 60 },
  bannerImage: { width: '100%', height: 200, borderRadius: 0 },
  bannerFallback: { backgroundColor: prism.card },
  bannerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center' },
  overlayCircle: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(8, 13, 16, 0.78)', borderWidth: 1, borderColor: prism.border },
  avatarWrapper: { position: 'absolute', left: 20, bottom: -50 },
  avatarButton: { borderRadius: 8, borderWidth: 2, borderColor: prism.background, padding: 2, backgroundColor: prism.background },
  avatar: { width: 100, height: 100, borderRadius: 8, backgroundColor: prism.cardDeep },
  avatarPlaceholder: { alignItems: 'center', justifyContent: 'center', backgroundColor: prism.card },
  avatarCamera: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center' },
  formSection: { paddingHorizontal: 20 },
  label: { color: prism.text, fontSize: 14, fontWeight: '600', marginBottom: 8 },
  input: { color: prism.text, backgroundColor: 'rgba(8, 13, 16, 0.86)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, borderWidth: 1, borderColor: prism.border },
  textarea: { minHeight: 100, textAlignVertical: 'top' },
  socialSection: { marginTop: 24, paddingHorizontal: 20 },
  sectionTitle: { ...theme.typography.label, color: prism.text, fontSize: 18, lineHeight: 22, fontWeight: '700', marginBottom: 12 },
  socialRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10 },
  socialCard: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, paddingHorizontal: 12, borderWidth: 1, borderColor: prism.border, borderRadius: 12, backgroundColor: 'rgba(8, 13, 16, 0.78)', marginBottom: 12 },
  socialIconWrap: { display: 'none' },
  socialBadge: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: prism.border, backgroundColor: prism.cardDeep },
  instagramBadge: { backgroundColor: '#dc2743' },
  outlinedBadge: { backgroundColor: prism.cardDeep, borderWidth: 1, borderColor: prism.border },
  socialContent: { flex: 1, minWidth: 0 },
  socialLabel: { color: prism.text, fontSize: 16, fontWeight: '600' },
  socialValue: { color: prism.muted, fontSize: 14 },
  charCount: { color: prism.muted, fontSize: 12, alignSelf: 'flex-end', marginTop: 4 },
  editButton: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(8, 13, 16, 0.86)', borderWidth: 1, borderColor: prism.border },
  footerActions: { gap: 12, paddingHorizontal: 20, marginTop: 24 },
  actionButton: { minHeight: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, overflow: 'hidden' },
  cancelButton: { backgroundColor: 'rgba(8, 13, 16, 0.86)', borderColor: prism.borderStrong },
  saveButton: { backgroundColor: prism.secondary, borderColor: prism.secondary, paddingVertical: 0 },
  disabledButton: { opacity: 0.5 },
  actionLabel: { color: prism.text, fontSize: 16, fontWeight: '700' },
  cancelLabel: { color: prism.textSoft },
  errorText: { color: '#FCA5A5', fontSize: 13, lineHeight: 18, textAlign: 'center' },
  saveGradient: { width: '100%', minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  savingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  savingLabel: { marginLeft: 8 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', alignItems: 'center', justifyContent: 'center' },
  modalCard: { width: '90%', maxWidth: 420, backgroundColor: prism.background, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: prism.border },
  modalTitle: { color: prism.text, fontSize: 18, fontWeight: '700', marginBottom: 12 },
  modalInput: { color: prism.text, backgroundColor: 'rgba(8, 13, 16, 0.86)', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, borderWidth: 1, borderColor: prism.border },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 16 },
  modalBtn: { flex: 1, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  modalCancel: { backgroundColor: 'rgba(8, 13, 16, 0.86)', borderWidth: 1, borderColor: prism.border },
  modalSave: { backgroundColor: prism.secondary },
  modalBtnLabel: { color: prism.text, fontSize: 15, fontWeight: '600' },
  modalHelper: { color: prism.muted, fontSize: 12, marginTop: 8 },
});
